'\" t
.\"     Title: alock
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.0 <http://docbook.sf.net/>
.\"      Date: 01/06/2015
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ALOCK" "1" "01/06/2015" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
alock \- locks the local X display until the correct password is entered
.SH "SYNOPSIS"
.sp
\fBalock\fR [\-help] [\-modules] [\-auth type:opts] [\-bg type:opts] [\-cursor type:opts] [\-input type:opts]
.SH "DESCRIPTION"
.sp
\fBAlock\fR is a simple screen lock application, which locks the X server until the correct password is provided\&. If the authentication was successful, the X server is unlocked and the user can continue to work\&. When \fBalock\fR is started it just waits for the first keypress\&. This first keypress is to indicate that the user now wants to type in the password\&. Such a behavior might seem to be annoying at the first glance, however this approach is chosen due to security reasons\&.
.sp
Note, that \fBalock\fR does not provide any fancy animations like \fIxlock\fR and \fIxscreensaver\fR and probably never will\&. It\(cqs just for locking the current X session\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-help\fR
.RS 4
Print a short help
.RE
.PP
\fB\-m\fR, \fB\-modules\fR
.RS 4
List available (compiled in) module types
.RE
.PP
\fB\-a\fR, \fB\-auth\fR \fItype:options\fR
.RS 4
Define the type of the authentication, depends strongly on how alock was built:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
none \- No authentication at all
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pam \- Tries to authenticate against the users system\-password using the
\fIpam\-login\fR\-module\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
passwd \- Tries to authenticate against the users system\-password\&. On systems using
\fIshadow\fR
alock needs the suid\-flag set\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
hash \- Authenticates using arbitrary hash comparison\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
list \- display available hashing algorithms
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
type=<type> \- use <type> hashing algorithm
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
hash=<hash> \- use <hash> as reference
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
file=<filename> \- use content of <filename> as reference
.RE
.RE
.RE
.PP
\fB\-b\fR, \fB\-bg\fR \fItype:options\fR
.RS 4
Define the type of how alock should handle the background:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
none \- You can see everything like it is
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
blank \- Fill the background with color
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
color=<color> \- use <color>
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
shade \- Dims content of the screen and recolors it\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
color=<color> \- use <color>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
shade=<percent> \- valid from 1 to 99
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
image \- Use the image <filename> and puts it as the background
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
file=<filename>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
center
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
scale
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
tiled
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
color=<color> \- use <color>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
shade=<percent> \- valid from 1 to 99
.RE
.RE
.RE
.PP
\fB\-c\fR, \fB\-cursor\fR \fItype:options\fR
.RS 4
Define the look\-a\-like of the cursor/mouse pointer:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
none \- No change to the current cursor
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
glyph \- Use the given glyph of the "cursor"\-font
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
list \- Display all possible glyph\-names
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
name=<name>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
bg=<color>
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
fg=<color>
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
xcursor \- Use the given <filename> in xcursor\-format
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
file=<filename>
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
image \- Use the given <filename>
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
file=<filename>
.RE
.RE
.RE
.PP
\fB\-i\fR, \fB\-input\fR \fItype:options\fR
.RS 4
Define the type of the input indicator, which should be used while typing password:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
none \- No input feedback for user
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
frame \- Display frame on the current display
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
width=<width> \- the frame width, valid from 1 upwards
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
input=<color> \- use <color> while typing
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
check=<color> \- use <color> while checking password
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
error=<color> \- use <color> upon authentication error
.RE
.RE
.RE
.SH "RESOURCES"
.PP
\fBALock\&.Background\&.Blank\&.Color\fR
.RS 4
Same as
\fB\-b blank:color\fR\&. X color resource name\&.
.RE
.PP
\fBALock\&.Background\&.Image\&.Color\fR
.RS 4
Same as
\fB\-b image:color\fR\&. X color resource name\&.
.RE
.PP
\fBALock\&.Background\&.Image\&.Shade\fR
.RS 4
Same as
\fB\-b image:shade\fR\&. Numerical\&.
.RE
.PP
\fBALock\&.Background\&.Image\&.Option\fR
.RS 4
Same as
\fB\-b image:center\fR,
\fB\-b image:scale\fR
or
\fB\-b image:tiled\fR\&. Available option values:
\fBcenter\fR,
\fBscale\fR,
\fBtiled\fR
.RE
.PP
\fBALock\&.Background\&.Shade\&.Color\fR
.RS 4
Same as
\fB\-b shade:color\fR\&. X color resource name\&.
.RE
.PP
\fBALock\&.Background\&.Shade\&.Shade\fR
.RS 4
Same as
\fB\-b shade:shade\fR\&. Numerical\&.
.RE
.PP
\fBALock\&.Cursor\&.Glyph\&.Name\fR
.RS 4
Same as
\fB\-c glyph:name\fR\&. Compiled\-in glyph name\&.
.RE
.PP
\fBALock\&.Cursor\&.Glyph\&.Background\fR
.RS 4
Same as
\fB\-b glyph:bg\fR\&. X color resource name\&.
.RE
.PP
\fBALock\&.Cursor\&.Glyph\&.Foreground\fR
.RS 4
Same as
\fB\-b glyph:fg\fR\&. X color resource name\&.
.RE
.PP
\fBALock\&.Input\&.Frame\&.Color\&.Input\fR
.RS 4
Same as
\fB\-i frame:input\fR\&. X color resource name\&.
.RE
.PP
\fBALock\&.Input\&.Frame\&.Color\&.Check\fR
.RS 4
Same as
\fB\-i frame:check\fR\&. X color resource name\&.
.RE
.PP
\fBALock\&.Input\&.Frame\&.Color\&.Error\fR
.RS 4
Same as
\fB\-i frame:error\fR\&. X color resource name\&.
.RE
.PP
\fBALock\&.Input\&.Frame\&.Width\fR
.RS 4
Same as
\fB\-i frame:width\fR\&. Numerical\&.
.RE
.SH "AUTHOR"
.sp
Originally written by Mathias Gumz <akira at fluxbox\&.org>, based upon xtrlock\&. Starting with alock version 2\&.0, code is maintained by Arkadiusz Bokowy <arkadiusz\&.bokowy at gmail\&.com>\&.
.SH "COPYING"
.sp
Copyright (C) 2005 \- 2009 Mathias Gumz, 2014 Arkadiusz Bokowy\&. Free use of this software is granted under the terms of the MIT\&. See LICENSE provided in the distribution\&.
